# -*- coding: utf-8 -*-
"""API_Performance_Monitor

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-YyO21utrBG6x247X77MiAZsabYLtxU0
"""

import requests
import time
import pandas as pd

websites = [
    "https://www.google.com",
    "https://github.com",
    "https://openai.com"
]

results = []

for site in websites:
    start = time.time()

    response = requests.get(site)

    end = time.time()

    response_time = round(end - start, 3)

    results.append([site, response.status_code, response_time])

df = pd.DataFrame(
    results,
    columns=["Website", "Status Code", "Response Time (sec)"]
)

print(df)